### ISSUE TITLE
Problems when login

### ISSUE THREAD

**Issue by sebastianbouckaert** [ieski/OdooXmlRpc#1]
I receive an error:
"response contains boolean value where integer expected [response]"

The error occurs when I'm executing this call:
_rpcConnectionSchema.UserId = loginRpc.login(_rpcConnectionSchema.DbName, _rpcConnectionSchema.DbUser, _rpcConnectionSchema.DbPassword);

**Comment by ieski** [comment]
Hi,

Problem was solved.

Thanks.

**Comment by sebastianbouckaert** [comment]
I still receive the issue but I don't know if it is the code or my credentials.
But the code could use better error handling? I found something regarding the error that the password should be changed first ... I' m looking into this

**Comment by sebastianbouckaert** [comment]
I checked the credentials and they are correct.
In the settings you ask for a ServerUrl, does this just mean the ip adress or ....

**Comment by sebastianbouckaert** [comment]
Credentials are ok, but still receive the same error...

**Comment by ieski** [comment]
What's the version of Odoo?

Sample config:
```
  var rpcConnnectionSettings = new RpcConnectionSetting
            {
                DbName = "test",
                DbUser = "admin",
                DbPassword = "admin,
                ServerUrl = "https://odoo.com",
                ImmediateLogin = true,
                ServerCertificateValidation = true
            };
```

**Comment by sebastianbouckaert** [comment]
The user you are taling about, are those actual database users or users from Odoo ?
There is a difference so I was just wondering

**Comment by ieski** [comment]
must be odoo user for xmlrpc connection

**Comment by sebastianbouckaert** [comment]
I getting connected , so thanks for the great work already:
The issue for me was this  ' rpcContext.AddField("image_medium");' , I think the field is not present in my environment. But I'm completly new to Odoo so 
But it seems I cannot add any fields except the id, I went to take a peek in the database and I assume that the field are the column names but no succes...

So I receive this error:

fault response contains string value where integer expected [fault response : struct mapped to type Fault : member faultCode mapped to type Int32]


If I add more then one field

**Comment by ieski** [comment]
Hi Sebastian;
I glad you work.

Do you know filestore? Odoo saves some fields in filestore. 
Example like "image_medium" field in "hr.employee" table.
return false If filed is null

some fields in the hr.employee model
image_1024 | Image 1024 | binary | ​ | ​ | ​ | Base Field
image_128 | Image 128 | binary | ​ | ​ | ​ | Base Field
image_1920 | Image | binary | ​ | ​ | ​ | Base Field
image_256 | Image 256 | binary | ​ | ​ | ​ | Base Field
image_512 | Image 512 | binary | ​ | ​ | ​ | Base Field
name | Employee Name | char | ​ | ​ | ​ | Base Field

```
            var rpcContext = new RpcContext(odooConn, "hr.employee");

            rpcContext
                .RpcFilter.NotEqual("image_512", false);

            rpcContext
                .AddField("id")
                .AddField("name")
                .AddField("image_512");

            var data = rpcContext.Execute(true);

            foreach (var record in data.ToList())
            {
                var image = "";
                if (record.GetValue("image_512") != null)
                {
                    image = record.GetValue("image_512").ToString();
                }
                
                if (image.Length <= 0) continue;

                var id = record.GetValue("id").ToString();
                var name = record.GetValue("name").ToString();
            }
```

**Comment by ieski** [comment]
If you want to get the names and properties of all fields and check them
```
            var fields = rpcContext.GetFields(); // returns FieldAttribute (FieldName, Type, Help, String)
            foreach (var field in fields)
            {
                rpcContext.AddField(field.FieldName);
            }
//or
            rpcContext.AddFields(fields.Select(f => f.FieldName).ToList());
```

**Comment by ieski** [comment]
commit new codes

**Comment by sebastianbouckaert** [comment]
For me it now failes on this:


    public int[] Search(string model, object[] filter, int? offset = null, int? limit = null)
        {
            if (offset == null || limit == null)
            {
                return _objectRpc.search(_rpcConnectionSchema.DbName, _rpcConnectionSchema.UserId, _rpcConnectionSchema.DbPassword, model, "search", filter);
            }
            return _objectRpc.search(_rpcConnectionSchema.DbName, _rpcConnectionSchema.UserId, _rpcConnectionSchema.DbPassword, model, "search", filter, (int)offset, (int)limit);
        }

        public object[] SearchAndRead(string model, object[] filter, object[] fields, int? offset = null, int? limit = null)
        {
            if (offset == null || limit == null)
            {
                return _objectRpc.search_read(_rpcConnectionSchema.DbName, _rpcConnectionSchema.UserId, _rpcConnectionSchema.DbPassword, model, "search_read", filter, fields);
            }

            return _objectRpc.search_read(_rpcConnectionSchema.DbName, _rpcConnectionSchema.UserId, _rpcConnectionSchema.DbPassword, model, "search_read", filter, fields, (int)offset, (int)limit);
        }



And I'm only asking for the id field

      var rpcContext = new RpcContext(odooConn, "hr.employee");
            rpcContext.RpcFilter.NotEqual("x_emp_uniqueid", false);
            rpcContext.AddField("id");

**Comment by sebastianbouckaert** [comment]
Okey I'm able to retrieve records now, finally, but II receive no additional fields...

![image](https://user-images.githubusercontent.com/20515102/76515829-96ea6780-645a-11ea-9f6c-f4df3453161f.png)

This is what I'm requesting

            var rpcContext = new RpcContext(odooConn, "hr.employee");
            rpcContext.RpcFilter.NotEqual("id", false);
            rpcContext.RpcFilter.NotEqual("image_medium", false);
            rpcContext.RpcFilter.NotEqual("name", false);
            rpcContext.AddField("id");
            rpcContext.AddField("image_medium");
            rpcContext.AddField("name");

**Comment by sebastianbouckaert** [comment]
the fields are always empty for me, but I can actually retrieve data, I only just receive the 'id' column, the rest of the columns are not loaded

**Comment by ieski** [comment]
Hey Sebastian,

I refactored all the code.
Thank you for your feedback.
I think the sample codes are explanatory enough.
